/**
 * Read-time resolution of Board ids → agoricNames labels for Zoe offers.
 *
 * Backed by the committed `src/config/agoricNames.json` (generated by scripts/refreshAgoricNames.ts).
 * Pure JSON import — no @endo / network at runtime, so this is safe in the Next.js read path and in
 * the indexer alike. Unknown Board ids return null; callers display the raw Board id as a fallback.
 */
import agoricNames from "@/config/agoricNames.json";

export interface VbankAssetMeta {
  readonly denom: string;
  readonly issuerName: string;
  readonly decimalPlaces: number;
}

const INSTANCES: Readonly<Record<string, string>> = agoricNames.instances ?? {};
const BRANDS: Readonly<Record<string, string>> = agoricNames.brands ?? {};
const VBANK_ASSETS: Readonly<Record<string, VbankAssetMeta>> =
  (agoricNames as { vbankAssets?: Record<string, VbankAssetMeta> }).vbankAssets ?? {};

/** Contract Instance name for a Board id (e.g. "board02568" → "psm-IST-USDC_grv"), or null. */
export function instanceName(boardId: string | null | undefined): string | null {
  if (!boardId) return null;
  return INSTANCES[boardId] ?? null;
}

/** Issuer Brand name for a Board id (e.g. "board0257" → "IST"), or null. */
export function brandName(boardId: string | null | undefined): string | null {
  if (!boardId) return null;
  return BRANDS[boardId] ?? null;
}

/** Fungible vbank denom for a Brand board id (e.g. "board0257" → "uist"), or null if not a vbank asset. */
export function brandDenom(boardId: string | null | undefined): string | null {
  if (!boardId) return null;
  return VBANK_ASSETS[boardId]?.denom ?? null;
}

/** Full vbank asset metadata (denom + issuerName + decimals) for a Brand board id, or null. */
export function brandAssetMeta(boardId: string | null | undefined): VbankAssetMeta | null {
  if (!boardId) return null;
  return VBANK_ASSETS[boardId] ?? null;
}

/** When the map was generated (for staleness display). */
export const AGORIC_NAMES_GENERATED_AT: string =
  (agoricNames as { generatedAt?: string }).generatedAt ?? "";
