/**
 * Refresh the committed Board-id → name map used to label Zoe offers by contract Instance / Brand.
 *
 * Reads `published.agoricNames.instance` and `.brand` from vstorage, unmarshals the CapData entry
 * lists (`[[name, remotable], …]`), and writes `src/config/agoricNames.json`. The read/UI path
 * imports that JSON only — no @endo at runtime in Next. Re-run on demand and as part of a reindex
 * (new contracts added after generation show as their raw Board id until refreshed).
 *
 * Uses the no-lockdown @endo shims (via walletOfferMarshal). Run:
 *   RPC_URL=... npx tsx scripts/refreshAgoricNames.ts
 */
import "dotenv/config";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { toHex, fromBase64 } from "@cosmjs/encoding";
import { QueryDataRequest, QueryDataResponse } from "@agoric/cosmic-proto/vstorage/query.js";
import { parseCapData } from "../src/lib/walletOfferMarshal";
import { BoardSlot } from "../src/lib/walletOfferTypes";
import { rpcCallWithFallback } from "../src/lib/rpc";

const RPC_URLS = [process.env.RPC_URL ?? "https://main-a.rpc.agoric.net", process.env.RPC_URL_FALLBACK ?? ""];
const OUT_PATH = resolve(__dirname, "../src/config/agoricNames.json");

interface AbciQueryResponse {
  readonly response: { readonly value?: string; readonly code?: number; readonly log?: string };
}

/** Latest vstorage value at `path` (the most recent entry of the StreamCell). */
async function vstorageLatest(path: string): Promise<string> {
  const reqBytes = QueryDataRequest.encode(QueryDataRequest.fromPartial({ path })).finish();
  const res = await rpcCallWithFallback<AbciQueryResponse>(RPC_URLS, "abci_query", {
    path: "/agoric.vstorage.Query/Data",
    data: toHex(reqBytes),
    prove: false,
  });
  if (!res.response?.value) {
    throw new Error(`vstorage ${path}: empty (code=${res.response?.code} log=${res.response?.log})`);
  }
  const streamCellJson = QueryDataResponse.decode(fromBase64(res.response.value)).value;
  const cell = JSON.parse(streamCellJson) as { values?: string[] };
  const values = cell.values ?? [];
  if (values.length === 0) throw new Error(`vstorage ${path}: StreamCell has no values`);
  return values[values.length - 1]!;
}

/** Decode an agoricNames node (`[[name, remotable], …]`) into a { boardId: name } map. */
function entriesToBoardMap(plain: unknown): Record<string, string> {
  const out: Record<string, string> = {};
  if (!Array.isArray(plain)) return out;
  for (const entry of plain) {
    if (!Array.isArray(entry) || entry.length < 2) continue;
    const [name, ref] = entry;
    if (typeof name === "string" && ref instanceof BoardSlot) out[ref.boardId] = name;
  }
  return out;
}

export interface VbankAssetMeta {
  readonly denom: string;
  readonly issuerName: string;
  readonly decimalPlaces: number;
}

/**
 * Decode `published.agoricNames.vbankAsset` (`[[denom, { brand, displayInfo, issuerName }], …]`) into
 * a { brandBoardId: { denom, issuerName, decimalPlaces } } map — the brand → fungible-asset link used
 * to value offer give/want/payout amounts in USD via the existing denom-keyed pricing path.
 */
function entriesToVbankMap(plain: unknown): Record<string, VbankAssetMeta> {
  const out: Record<string, VbankAssetMeta> = {};
  if (!Array.isArray(plain)) return out;
  for (const entry of plain) {
    if (!Array.isArray(entry) || entry.length < 2) continue;
    const [denom, rec] = entry;
    if (typeof denom !== "string" || typeof rec !== "object" || rec === null) continue;
    const r = rec as { brand?: unknown; displayInfo?: { decimalPlaces?: unknown }; issuerName?: unknown };
    if (!(r.brand instanceof BoardSlot)) continue;
    const dp = r.displayInfo?.decimalPlaces;
    out[r.brand.boardId] = {
      denom,
      issuerName: typeof r.issuerName === "string" ? r.issuerName : "",
      decimalPlaces: typeof dp === "number" && Number.isFinite(dp) ? dp : 6,
    };
  }
  return out;
}

async function main() {
  const [instanceRaw, brandRaw, vbankRaw] = await Promise.all([
    vstorageLatest("published.agoricNames.instance"),
    vstorageLatest("published.agoricNames.brand"),
    vstorageLatest("published.agoricNames.vbankAsset"),
  ]);

  const instances = entriesToBoardMap(parseCapData(instanceRaw));
  const brands = entriesToBoardMap(parseCapData(brandRaw));
  const vbankAssets = entriesToVbankMap(parseCapData(vbankRaw));

  if (Object.keys(instances).length === 0) throw new Error("no instances decoded — aborting (would clobber map)");

  const payload = {
    _comment:
      "Board-id → agoricNames map for labeling Zoe offers (src/lib/agoricInstanceNames.ts). vbankAssets maps a Brand board id → its fungible denom + decimals for USD offer valuation. Generated by scripts/refreshAgoricNames.ts; refresh on reindex.",
    generatedAt: new Date().toISOString(),
    chainId: "agoric-3",
    instances,
    brands,
    vbankAssets,
  };
  writeFileSync(OUT_PATH, JSON.stringify(payload, null, 2) + "\n");
  console.log(
    `Wrote ${OUT_PATH}: ${Object.keys(instances).length} instances, ${Object.keys(brands).length} brands, ${Object.keys(vbankAssets).length} vbank assets`
  );
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e instanceof Error ? e.message : e);
    process.exit(1);
  });
